# Generated by Django 3.1.1 on 2020-10-20 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200929_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='app.flashcard'),
        ),
    ]
